# PowerProtect Data Manager
dmUser: admin
dmPassword: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  <encrypted-in-ansible-vault>

adAdmin: administrator@{{domain}}
adPassword: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  <encrypted-in-ansible-vault>

wsAdmin: administrator
wsPassword: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  <encrypted-in-ansible-vault>