---
- name: "Demo AD HOC backup of a protection policy"
  hosts: localhost
  collections:
    - community.general
  gather_facts: false

  # Playbook variables
  vars:
    anMsgTitle: "( Ansible : v2.6 )"
    anMsgContent:
      - "set_fact content"
    dmMsgTitle: "( {{dmHost}} : v{{dmVersion}} )"
    dmMsgContent:
      - "Wait for HTTPS connectivity on port {{dmPort}}"
      - "Login to Data Manager REST API"
      - "Query for the protection policy"
      - "Start the backup for the protection policy"
      - "Logout out of the Data Manager REST API"
  vars_files:
    - vars/vault.yaml
    - vars/environment.yaml

  tasks:
  # Check for connectivity
  - name: "{{ dmMsgTitle }}: {{ dmMsgContent[0] }}"
    wait_for:
      host: "{{dmHost}}"
      port: "{{dmPort}}"
      state: started
      delay: 1
      sleep: 60
      timeout: 600
    register: testApiPort
  
  # Authenticate to the REST API
  - name: "{{ dmMsgTitle }}: {{ dmMsgContent[1] }}"
    uri:
      url: "{{dmBaseUrl}}/v{{version}}/{{endpoint}}"
      method: POST
      validate_certs: no
      return_content: yes
      body_format: json
      body:
        username: "{{dmUser}}"
        password: "{{dmPassword}}"
      status_code: 200
    vars:
      endpoint: login
      version: 2
    register: token

  # Ansible set_fact
  - name: "{{ anMsgTitle }}: {{ anMsgContent[0] }}"
    ansible.builtin.set_fact:
      apiToken: "{{token.json.access_token}}"

  # START THE WORKFLOW
  # REST API query
  - name: "{{ dmMsgTitle }}: {{ dmMsgContent[2] }}"
    uri:
      url: "{{dmBaseUrl}}/v{{version}}/{{endpoint}}?filter={{filter}}"
      headers:
        Authorization: "Bearer {{apiToken}}"
        Content-Type: "application/json"
      method: GET
      validate_certs: no
      return_content: yes
      body_format: json
    vars:
      endpoint: protection-policies
      version: 3
      filters: 
        - name eq "{{ dmPolicyName }}"
      filter: "{{ filters | join(' ') | urlencode() }}"
    register: policies

  # Ansible set_fact
  # NOTE: This is temp until I can get jmespath working
  - name: "{{ anMsgTitle }}: {{ anMsgContent[0] }}"
    ansible.builtin.set_fact:
      policyId: "{{ policies.json.content[0].id }}"

  # Ansible set_fact
  # NOTE: This is temp until I can get jmespath working
  - name: "{{ anMsgTitle }}: {{ anMsgContent[0] }}"
    ansible.builtin.set_fact:
      backupId: "{{ policies.json.content[0].objectives[0].id }}"

  - name: "{{ dmMsgTitle }}: {{ dmMsgContent[3] }}"
    uri:
      url: "{{dmBaseUrl}}/v{{version}}/{{endpoint}}"
      headers:
        Authorization: "Bearer {{apiToken}}"
        Content-Type: "application/json"
      method: POST
      validate_certs: no
      return_content: yes
      body_format: json
      body:
        source:
          assetIds: null
          protectionGroupIds: []
        policy:
          id: "{{ policyId }}"
          objectives:
            - id: "{{ backupId }}"
              operation:
                backupLevel: "{{ dmBackupLevel }}"
              retentions:
              - time:
                - type: RETENTION
                  unitValue: 7
                  unitType: DAY
      status_code: 202
    vars:
      endpoint: protections
      version: 3
  # END THE WORKFLOW

  # Log out of the REST API
  - name: "{{ dmMsgTitle }}: {{ dmMsgContent[-1] }}"
    uri:
      url: "{{dmBaseUrl}}/v{{version}}/{{endpoint}}"
      headers:
        Authorization: "Bearer {{apiToken}}"
        Content-Type: "application/json"
      method: POST
      validate_certs: no
      return_content: yes
      body_format: json
      status_code: 204
    vars:
      endpoint: logout
      version: 2